services:
  postgres:
    container_name: postgres-container
    image: postgres
    volumes:
      - /data/postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: amam
      POSTGRES_PASSWORD: amam
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
  pgadmin:
    container_name: pgadmin-container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-amam}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    restart: unless-stopped
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - postgres
networks:
  postgres:
    driver: bridge
volumes:
  postgres:
  pgadmin:

